# -*- coding: utf-8 -*-
"""Gaea 0.65.0 — bereidingswijzen bij elke medicinale soort.
Op het blad stond wel waarvoor een soort werd gebruikt, maar niet hoe je hem
verwerkt. Dat is nu een eigen sectie: thee, tinctuur, olie, zalf, siroop,
stoombad of kompres, met de verhouding en de trektijd erbij. Waar iets alleen
uitwendig mag, staat dat er nadrukkelijk bij."""
import sys
src = sys.argv[1] if len(sys.argv) > 1 else "index.html"
s = open(src, encoding="utf-8").read()
def rep(hay, old, new, n=1):
    c = hay.count(old); assert c == n, f"{c}x: {old[:80]!r}"
    return hay.replace(old, new)

B = {
"daslook":"Vers door pesto, boter of azijn; de zwavelverbindingen breken bij verhitting af, dus rauw verwerken. Drogen heeft geen zin \u2014 dan blijft er niets van over.",
"brandnetel":"Thee: 2 tl gedroogd blad per kop, 10 min trekken. Gekookt als groente. Vers sap uit de sapcentrifuge. Blad blancheren doodt de brandharen.",
"vogelmuur":"Rauw door salade. Uitwendig: vers gekneusd blad als kompres, of trek het in olie voor een zalf bij jeuk en schrale huid.",
"hondsdraf":"Thee van vers of gedroogd kruid, 1 tl per kop, 5 min \u2014 langer wordt bitter. Ook als kruiderij in soep.",
"kleefkruid":"Koud getrokken: een handvol vers kruid een nacht in koud water. Verhitten breekt de werkzame stoffen af. Jong ook door een groene sapmix.",
"herderstasje":"Thee van het verse kruid, 2 tl per kop, 10 min. Werkt vers veel beter dan gedroogd; het gedroogde kruid verliest snel kracht.",
"weegbree":"Vers blad kneuzen en direct op de huid bij insectenbeten. Inwendig: thee van 1 el blad, of siroop met honing bij hoest.",
"groteweegbree":"Als smalle weegbree: vers kompres of hoestsiroop met honing. Het zaadslijm werkt als milde vezel bij trage stoelgang.",
"madeliefje":"Thee van bloemhoofdjes, 1 el per kop. Uitwendig als kompres of in olie getrokken zalf bij blauwe plekken.",
"paardenbloem":"Wortelthee: 1 tl gedroogde wortel per kop, 10 min zachtjes koken. Geroosterde wortel als koffie. Blad rauw of gestoofd.",
"kleinhoefblad":"Uitsluitend als afgemeten, kortdurende thee van de bloemen; door de leveralkalo\u00efden hooguit een paar dagen aaneen en niet tijdens zwangerschap.",
"klit":"Wortelafkooksel: 1 el per half liter, 15 min koken. Uitwendig als spoeling bij huidklachten; de wortel ook gestoofd als groente.",
"duizendblad":"Thee van bloeiend kruid, 1 el per kop, 10 min afgedekt. Tinctuur 1:5 in 40% alcohol. Uitwendig als kompres bij wondjes.",
"brunel":"Thee of gorgeldrank van het bloeiende kruid, 2 tl per kop. Bij keelpijn lauw gorgelen, niet doorslikken maar uitspugen.",
"cichorei":"Wortel roosteren en malen als koffievervanger; als bittermiddel een afkooksel van 1 tl per kop, 10 min zachtjes koken.",
"bijvoet":"Kruiderij bij vet vlees. Thee spaarzaam, 1 tl per kop; niet tijdens zwangerschap. Ook als r\u00f6ker- of wierookkruid gedroogd.",
"boerenwormkruid":"Uitsluitend uitwendig: gedroogd tussen kleding tegen motten, of als aftreksel als vlooienmiddel voor de mand. Inwendig niet, thujon is te riskant.",
"heermoes":"Afkooksel, geen aftreksel: 1 el gedroogd kruid twintig minuten koken, anders komt het kiezelzuur niet vrij. Hooguit enkele weken aaneen.",
"sintjanskruid":"Rode olie: verse bloemen in olijfolie, drie weken op de vensterbank tot hij dieprood is. Thee 1 tl per kop. Let op wisselwerking met medicijnen.",
"kamille":"Thee: 1 el bloemen per kop, afgedekt 8 min \u2014 zonder deksel vervliegt de olie. Stoombad bij verkoudheid, kompres bij ontstoken huid.",
"moerasspirea":"Thee van de bloemen, 1 el per kop, afgedekt en niet koken: de salicylverbindingen vervliegen. Ook als aroma in siroop en mede.",
"valeriaan":"Koud getrokken wortel: 1 tl in een kop koud water, 8 tot 12 uur. Warm trekken maakt hem bitterder. Tinctuur 1:5 in 60% alcohol.",
"marjolein":"Thee van 1 tl gedroogd kruid, 5 min afgedekt. Als kruiderij op het einde toevoegen; de olie vervliegt bij lang koken.",
"tijm":"Thee: 1 tl per kop, afgedekt 8 min. Stoombad bij vastzittende hoest. Siroop met honing. Tinctuur 1:5 in 45% alcohol.",
"melisse":"Vers blad, 2 el per kop, 5 min afgedekt \u2014 gedroogd verliest hij snel geur. Ook koud getrokken in water, of in olie voor een zalf bij koortslip.",
"watermunt":"Thee van vers of gedroogd blad, afgedekt 5 min. Spaarzaam: sterker van smaak dan pepermunt.",
"kaasjeskruid":"Koud trekken: 1 el blad of bloem in koud water, 2 uur. Warm getrokken verdwijnt het slijm dat juist de keel verzacht.",
"heemst":"Wortel koud trekken, 6 tot 8 uur, dan lauw drinken. Nooit koken. Bij hoest en maagirritatie; houd een uur afstand van andere medicijnen.",
"smeerwortel":"Alleen uitwendig: wortel in olie trekken en tot zalf verwerken, of vers geraspt als kompres. Niet op open wonden en niet inwendig.",
"stinkendegouwe":"Alleen uitwendig en spaarzaam: het verse oranje sap op een wrat, punt voor punt. Niet op gezonde huid en niet inwendig.",
"agrimonie":"Thee van het bloeiende kruid, 1 el per kop, 10 min. Als gorgeldrank bij keelpijn en als kompres bij kleine wonden.",
"engelwortel":"Wortelafkooksel als bittermiddel, 1 tl per kop, 10 min. Jonge stengels gekonfijt. Wortel ook als aroma in kruidenbitter.",
"hop":"Koud of lauw getrokken bellen, 1 el per kop \u2014 kokend water maakt hem hard bitter. Ook als kussenvulling bij slecht slapen.",
"vlier":"Bloesem: siroop of thee, 2 el per kop, afgedekt. Bessen altijd verhitten tot siroop of stroop; rauw geven ze braken.",
"meidoorn":"Thee van blad, bloem en bes samen, 1 el per kop, 10 min. Tinctuur 1:5. Werkt traag: reken op weken, niet op dagen.",
"hondsroos":"Bottels: zaadpluis verwijderen, dan siroop, gelei of thee. Niet boven de 70 graden verhitten, dan gaat de vitamine C verloren.",
"braam":"Blad als thee, 1 el per kop, 10 min; samentrekkend bij diarree. Gefermenteerd blad geeft een zwarte-theeachtige drank.",
"framboos":"Bladthee, 1 el per kop, 10 min. In de laatste weken van een zwangerschap traditioneel gebruikt \u2014 daarvoor niet.",
"bosbes":"Gedroogde bessen als afkooksel bij diarree, 1 el per kop, 10 min koken. Verse bessen werken juist andersom.",
"linde":"Bloesemthee, 1 el per kop, afgedekt 8 min. Zweetdrijvend, dus warm drinken en daarna warm blijven.",
"berk":"Bladthee, 2 tl per kop. Sap aftappen in maart, hooguit een liter per boom, en de wond meteen dichten met was.",
"grovden":"Meischeuten als siroop met suiker, laagje om laagje, drie weken. Naaldthee, 1 tl per kop. Stoombad bij verkoudheid.",
"judasoor":"Weken tot hij opzwelt, dan meekoken in soep of roerbak. Medicinaal vooral als voedingsmiddel, niet als aftreksel.",
"berkenzwam":"Dun schaven en langdurig trekken, minstens een half uur; het is hout, geen kruid. Ook gedroogd en gemalen in thee.",
"elfenbankje":"Dubbel aftreksel: eerst een uur koken, dan de gezeefde massa in alcohol trekken en de twee mengen. Alleen zo komen zowel de suikers als de harsen mee.",
"dovenetel":"Bloementhee, 1 el per kop. Jonge toppen gekookt als groente. Uitwendig als kompres bij ontstoken huid.",
"raket":"Vers blad als kruiderij; medicinaal als siroop met honing bij heesheid \u2014 vandaar de oude naam zangerskruid.",
"klaproos":"Bloemblaadjes als thee of siroop, 1 tl per kop; mild kalmerend. De onrijpe zaaddoos hoort er niet in.",
"rodeklaver":"Bloemhoofdjes als thee, 1 el per kop, 10 min. Ook gedroogd door brood. Niet bij hormoongevoelige aandoeningen.",
"zilverschoon":"Thee van blad en wortel, 1 el per kop, 10 min. Sterk samentrekkend; ook als gorgeldrank.",
"tormentil":"Wortelafkooksel, 1 tl per kop, 10 min koken. Tinctuur als mondspoeling bij tandvleesontsteking; zeer looistofrijk.",
"bosaardbei":"Bladthee, 1 el per kop, 10 min. Alleen goed gedroogd of juist vers gebruiken; halfdroog blad kan schimmelen.",
"viooltje3":"Thee van bloem en blad, 1 el per kop, 10 min. Ook als siroop. Slijmoplossend bij droge hoest.",
"maartsviooltje":"Bloemsiroop of thee, 1 el per kop. Wortel niet gebruiken: die werkt braakverwekkend.",
"sleutelbloem":"Wortelafkooksel bij vastzittende hoest, 1 tl per kop, 10 min koken. In Nederland beschermd \u2014 alleen uit eigen tuin.",
"koningskaars":"Bloementhee, 1 el per kop, en altijd door een doek of koffiefilter zeven: de fijne haartjes prikkelen anders de keel.",
"klimop":"Uitsluitend uitwendig, en dan nog voorzichtig: een aftreksel als kompres. De gestandaardiseerde hoestdrank uit de apotheek is iets anders dan zelf trekken.",
"jeneverbes":"Bessen kneuzen, 1 tl per kop, 10 min trekken. Niet langer dan vier weken en niet bij nierklachten of zwangerschap.",
"kalmoes":"Wortelstok als bittermiddel, 1 tl per kop koud aanzetten en dan verwarmen. Alleen de Europese vorm; hooguit kortdurend.",
"blaaswier":"Gedroogd en gemalen als zoutvervanger, of als afkooksel. Rijk aan jodium: niet bij schildklierklachten of naast schildkliermedicatie.",
"wilg":"Bastafkooksel: 1 tl per kop, 10 min koken. Tinctuur 1:5. Niet bij aspirineovergevoeligheid en niet bij kinderen met koorts.",
"zwartebes":"Bladthee, 1 el per kop, 10 min. Bessen als siroop of gelei. Het blad werkt anders dan de bes: vochtafdrijvend in plaats van versterkend.",
"lakzwam":"Hard als hout: in dunne plakken een uur koken, of dubbel aftreksel met alcohol. Bitter; met gember of honing beter drinkbaar.",
"salie":"Thee, 1 tl per kop, afgedekt 8 min. Vooral als gorgeldrank bij keelpijn. Niet langdurig in hoge dosis en niet bij borstvoeding.",
"rozemarijn":"Thee, 1 tl per kop. In olie getrokken voor een spierzalf. Sterk verwarmend; niet vlak voor het slapengaan.",
"lavendel":"Bloemthee, 1 tl per kop, afgedekt 5 min. In olie getrokken tegen jeuk en insectenbeten; ook in een kussentje voor de nacht.",
"echtetijm":"Thee 1 tl per kop, stoombad bij verkoudheid, siroop met honing bij hoest. Tinctuur 1:5 in 45% alcohol.",
"peterselie":"Vers door het gerecht, op het laatst. Thee van de wortel als plasmiddel; niet tijdens zwangerschap in medicinale hoeveelheid.",
"dille":"Zaad als thee bij winderigheid, 1 tl gekneusd per kop. Blad vers, op het laatste moment \u2014 het verdraagt geen hitte.",
"venkel":"Zaad kneuzen, 1 tl per kop, 10 min afgedekt. Klassiek bij krampen en winderigheid, ook bij kleine kinderen in slappe thee.",
"koriander":"Zaad roosteren en malen als kruiderij; als thee 1 tl gekneusd zaad per kop bij een opgeblazen gevoel.",
"bonenkruid":"Meekoken met peulvruchten \u2014 daar komt de naam vandaan. Thee 1 tl per kop bij winderigheid.",
"pepermunt":"Thee 1 el vers of 1 tl gedroogd per kop, afgedekt 5 min. Niet bij maagzuurklachten: hij ontspant juist de maagmond.",
"citroenverbena":"Thee van gedroogd blad, 1 el per kop, afgedekt. Houdt zijn geur uitzonderlijk goed bij drogen.",
"goudsbloem":"Bloemblaadjes in olie trekken voor zalf bij schrale huid, of als thee 1 el per kop. Ook als kompres bij kleine wonden.",
"echinacea":"Tinctuur 1:5 uit de verse wortel; als thee minder krachtig. Kortdurend gebruiken, niet als vaste dagelijkse thee.",
"hysop":"Thee 1 tl per kop, afgedekt. Bij vastzittende hoest. Spaarzaam gebruiken: de olie bevat pinocamfon.",
"lavas":"Wortel als afkooksel, 1 tl per kop; blad als kruiderij in bouillon. Niet bij nierontsteking of vochtophoping door hartfalen.",
"alsem":"Uitsluitend als kort bittermiddel: enkele druppels tinctuur voor de maaltijd, of een zeer slappe thee. Nooit dagelijks en niet tijdens zwangerschap.",
"knoflook":"Rauw fijngesneden en tien minuten laten staan voordat je hem verhit; dan pas ontstaat de allicine. Ook in honing of azijn ingelegd.",
"mierikswortel":"Vers geraspt, direct gebruiken; de scherpte vervliegt binnen een half uur. Ingelegd in azijn blijft hij bruikbaar.",
"zoethout":"Wortelafkooksel, 1 tl per kop, 10 min koken. Hooguit vier tot zes weken: langdurig gebruik verhoogt de bloeddruk.",
"gember":"Vers geraspt als thee, 1 tl per kop, 10 min zachtzieden. Ook in siroop of als gekonfijte wortel bij misselijkheid.",
"kurkuma":"Met vet en zwarte peper samen gebruiken, anders neemt het lichaam nauwelijks curcumine op. Gouden melk of in het gerecht.",
"kaneel":"Als stokje meekoken in melk of thee. Kies Ceylonkaneel voor dagelijks gebruik; cassia bevat veel meer cumarine.",
"anijs":"Zaad kneuzen, 1 tl per kop, afgedekt 10 min. Ook als siroop bij prikkelhoest.",
"karwij":"Zaad kneuzen, 1 tl per kop, 10 min afgedekt. Meekoken met kool om winderigheid te dempen.",
"roomsekamille":"Thee van de bloemhoofdjes, 1 tl per kop, afgedekt \u2014 sterker en bitterder dan echte kamille, dus minder gebruiken.",
"passiebloem":"Thee van het gedroogde kruid, 1 el per kop, 10 min. Tinctuur 1:5. Kalmerend bij onrust en slecht inslapen.",
"vrouwenmantel":"Thee, 1 el per kop, 10 min. Sterk samentrekkend, ook als zitbad. Niet tijdens zwangerschap.",
"guldenroede":"Thee, 1 el per kop, 10 min; drink er ruim water bij. Klassiek nierkruid, niet bij vochtophoping door hartfalen.",
"berendruif":"Blad koud trekken, 12 uur \u2014 warm trekken haalt te veel looistof mee. Hooguit een week, en niet vaker dan vijf keer per jaar.",
"selderij":"Zaad als thee, 1 tl gekneusd per kop. Blad vers als kruiderij. Het maakt de huid lichtgevoelig, dus niet in grote hoeveelheid v\u00f3\u00f3r de zon in.",
"citroengras":"Stengel kneuzen en meekoken, of als thee 1 stengel per kop, 10 min. Ook als olie tegen muggen.",
"ginkgo":"Alleen gestandaardiseerd extract heeft zin; zelf blad trekken levert te weinig en het ruwe blad kan de huid prikkelen.",
"wijnruit":"Zeer spaarzaam en kortdurend, enkele druppels tinctuur. Maakt de huid sterk lichtgevoelig; niet tijdens zwangerschap.",
"aloe":"Alleen de heldere gel uit het blad, uitwendig op brandwondjes. De gele laag direct onder de schil is sterk laxerend en hoort eraf.",
"munt":"Thee van vers blad, 1 el per kop, afgedekt 5 min. Ook koud getrokken in water met citroen.",
"komijn":"Zaad roosteren en malen; als thee 1 tl gekneusd zaad per kop bij een zware maaltijd.",
"nigella":"Zaad geroosterd over brood, of een half theelepeltje olie per dag. Niet in medicinale hoeveelheid tijdens zwangerschap.",
"veldsalie":"Thee 1 tl per kop, afgedekt; milder dan echte salie. Ook als gorgeldrank.",
"scharlei":"Thee van blad of zaad, 1 tl per kop. Zaad in water geeft slijm dat uitwendig bij een geprikkeld oog werd gebruikt.",
"kattenkruid":"Thee 1 el per kop, afgedekt 5 min \u2014 niet koken, dan verdwijnt de nepetalacton. Kalmerend, ondanks het effect op katten.",
"tulsi":"Thee van vers of gedroogd blad, 1 el per kop, afgedekt. In India dagelijks gedronken; ook met gember en honing.",
"oostindischekers":"Vers blad en bloem door salade; de scherpe mosterdolie komt alleen rauw vrij. Zaad ingelegd als kappertjes.",
"mariadistel":"Zaad malen en direct gebruiken, 1 tl per dag; de olie wordt snel ranzig. Als thee weinig zinvol, silymarine lost slecht op in water.",
"duivelsklauw":"Wortelafkooksel, 1 tl per kop; bitter. Niet bij maagzweren. Werkt traag, reken op enkele weken.",
"kruidnagel":"Heel meekoken in stoofpot of thee. Kauwen op \u00e9\u00e9n nagel verdooft kiespijn tijdelijk; de olie onverdund prikkelt het slijmvlies.",
"kardemom":"Peulen kneuzen en meekoken in koffie, thee of rijst. Als thee 3 peulen per kop, 10 min.",
"wildetijm":"Thee 1 tl per kop, afgedekt; milder dan echte tijm. Ook als kruidenbad bij verkoudheid.",
"zenegroen":"Thee van het bloeiende kruid, 1 el per kop, 10 min. Traditioneel als wondkruid en gorgeldrank.",
"ereprijs":"Thee 1 el per kop, 10 min. Werd als theevervanger gedronken \u2014 de oude naam is Europese thee.",
"knoopkruid":"Thee van bloem en blad, 1 el per kop. Ook uitwendig als kompres bij kleine wonden.",
"kattenstaart":"Thee 1 el per kop, 10 min. Sterk samentrekkend bij diarree; ook als spoeling.",
"zwartemosterd":"Zaad malen en met lauw water tot pasta \u2014 niet met heet water, dan blijft de scherpte uit. Uitwendig hooguit een kwartier op de huid.",
"grotebevernel":"Wortelafkooksel, 1 tl per kop, 10 min koken. Traditioneel bij keelpijn en vastzittend slijm.",
"paardenkastanje":"Alleen uitwendig, en alleen als bereid extract in gel of zalf bij zware benen. Zelf zaden verwerken is niet zinvol en riskant.",
"rodebosbes":"Bessen als sap of moes; blad als afkooksel bij blaasklachten, kortdurend zoals berendruif.",
"wilgenroosje":"Bladthee, 1 el per kop; gefermenteerd blad geeft de Russische ivan-chai. Jonge scheuten als groente.",
"margriet":"Bloemhoofdjes als thee, 1 el per kop; knoppen ingelegd als kappertjes. Mild, in de hoek van kamille.",
"bosengelwortel":"Wortel als afkooksel bij een trage spijsvertering, 1 tl per kop. Zoals alle engelwortels: maakt de huid lichtgevoelig.",
"bospaardenstaart":"Als heermoes: minstens twintig minuten koken, niet trekken. Kortdurend gebruiken.",
"sponszwam":"Grondig spoelen, dan langdurig stoven; de lobben houden zand vast. Vooral voedsel, niet als aftreksel.",
"eikhaas":"Jonge randen bakken of stoven. Medicinaal als afkooksel of poeder in soep; verhitting maakt de b\u00e8ta-glucanen beschikbaar.",
"chaga":"Raspen en minstens een uur zachtjes trekken bij 70 tot 80 graden, niet koken. Ook dubbel aftreksel met alcohol. Niet bij nierstenen.",
"pruikzwam":"Bakken als vlees, of gedroogd en gemalen in soep. Extracten uit kweek zijn er ook; wilde exemplaren laten staan.",
"beukenzwam":"Altijd doorbakken, minstens acht minuten; rauw bitter. Vooral als voedsel, niet als thee.",
"zwartels":"Alleen uitwendig: bastafkooksel als spoeling bij keelpijn of op kleine wonden. Inwendig geeft het misselijkheid.",
"es":"Bladthee, 1 el per kop, 10 min. Bast als afkooksel bij koorts, in dezelfde traditie als wilg.",
"ratelpopulier":"Knoppen in olie of vet trekken voor zalf; bast als afkooksel, 1 tl per kop. Niet bij aspirineovergevoeligheid.",
"boswilg":"Bast als afkooksel, 1 tl per kop, 10 min koken. Katjes laten staan zolang er nog niets anders bloeit.",
"zwartepopulier":"De kleverige knoppen in olie of reuzel trekken op laag vuur: de klassieke populierzalf. Gebruik olie om de hars van je handen te krijgen.",
"vuilboom":"Alleen bast die minstens een jaar gedroogd is, als afkooksel \u2014 en dan nog hooguit een paar dagen. Vers werkt hij hevig braakverwekkend.",
"zuurbes":"Vruchtvlees als gelei of siroop, zaden eruit. De wortelbast met berberine is werk voor een apotheek, niet voor thuis.",
"appelbes":"Bessen als sap, siroop of gedroogd; rauw te samentrekkend. Verhitting maakt ze aangenamer zonder de anthocyanen te verliezen.",
"moerbei":"Bladthee, 1 el per kop, 10 min. Vruchten vers of als siroop. De bladthee is het medicinale deel, niet de bes.",
"lariks":"Meischeuten als siroop of in azijn. De hars uitsluitend uitwendig, verdund in zalf.",
"zilverspar":"Meischeuten als siroop of thee, 1 tl naalden per kop. Stoombad bij verkoudheid; niet bij kleine kinderen met astma.",
"struikhei":"Bloementhee, 1 el per kop, 10 min. Ook als aroma in bier en honing.",
"dophei":"Bloementhee als struikhei, 1 el per kop. Groeit op beschermde natte heide \u2014 herkennen en laten staan.",
"dropplant":"Thee van blad of bloem, 1 el per kop, afgedekt 5 min. Ook als siroop of in nagerechten; de smaak is sterk, dus spaarzaam.",
"bergamotplant":"Thee van blad en bloem, 1 el per kop, afgedekt. Bloemblaadjes rauw door salade.",
"shiso":"Vers blad bij vis en rijst; het rode blad ook als kleurstof bij het inmaken. Als olie afgeraden, als blad geen bezwaar.",
"tuinkers":"Kiemen op vochtig papier, na een week knippen. Vers gebruiken \u2014 verhitten haalt de scherpte eruit.",
"fenegriek":"Zaad roosteren voor gebruik, anders overheerst de bitterheid. Ook geweekt en gekiemd. Niet in medicinale hoeveelheid tijdens zwangerschap.",
"arnica":"Uitsluitend uitwendig: tinctuur 1:10 vertienvoudigd verdund als kompres, of kant-en-klare zalf op ongebroken huid. Nooit inwendig.",
"alant":"Wortelafkooksel, 1 tl per kop, 10 min koken; erg bitter, dus met honing. Ook als hoestsiroop of tinctuur 1:5.",
"honingklaver":"Alleen goed en snel gedroogd kruid als thee, 1 el per kop. Beschimmeld materiaal weggooien: dan ontstaat een bloedverdunner.",
"vlas":"Zaad malen of minstens een uur weken, met ruim water innemen. Heel doorslikken werkt niet. Hooguit twee eetlepels per dag.",
"ijzerhard":"Thee van het bloeiende kruid, 1 el per kop, 10 min; bitter. Niet tijdens zwangerschap.",
"saffraankrokus":"Enkele draadjes kort in warm water of melk laten trekken tot de kleur vrijkomt, dan meekoken. Milligrammen volstaan.",
"longkruid":"Thee van blad en bloem, 1 el per kop, 10 min. Niet dagelijks als vaste thee: het bevat sporen leveralkalo\u00efden.",
"roomsekervel":"Vers blad door rabarber of compote \u2014 dat halveert de suiker. Zaad als kruiderij, wortel gekookt.",
"lepelblad":"Vers blad rauw; verhitting breekt de vitamine C en de mosterdolie af. Een paar blaadjes door de salade volstaat.",
"kompassla":"Alleen het jonge rozetblad, rauw of gestoofd. Het ingedroogde melksap gold als slaapmiddel, maar dat is geen thuiswerk.",
"muizenoor":"Thee van het bloeiende kruid, 1 el per kop, 10 min. Niet langdurig dagelijks.",
"koninginnekruid":"Inwendig afgeraden door de leveralkalo\u00efden. Laat hem staan als vlinderplant; dat is zijn beste toepassing.",
"groothoefblad":"Alleen gestandaardiseerde, alkalo\u00efdvrije extracten uit de handel. Zelf blad of wortel trekken is levertoxisch.",
"tandzaad":"Thee van het bloeiende kruid, 1 el per kop, 10 min. Ook als badkruid bij ge\u00efrriteerde huid.",
"moerasandoorn":"Vers blad als kompres op kleine wonden. De knollen zijn voedsel, gekookt; de plant zelf is geen keukenkruid.",
"bosandoorn":"Uitwendig als kompres of wasing; de stank maakt hem inwendig onbruikbaar.",
"wolfspoot":"Alleen onder begeleiding: het remt de jodiumopname. Geen kruid om zelf thee van te zetten.",
"blauwglidkruid":"Thee van het bloeiende kruid, 1 el per kop, 10 min. Tinctuur 1:5. Kalmerend bij onrust.",
"malrove":"Thee 1 tl per kop; zo bitter dat hij altijd met honing of als siroop wordt gegeven \u2014 de klassieke malrovesnoepjes.",
"stinkendeballote":"Thee van het gedroogde kruid, 1 el per kop; drogen haalt de stank er grotendeels uit.",
"borstelkrans":"Thee van blad en bloem, 1 tl per kop, afgedekt. Milde marjoleinvervanger.",
"gamander":"Hooguit incidenteel als bittere thee, 1 tl per kop. Niet als vaste thee: sommige gamanders belasten de lever.",
"zeepkruid":"Uitwendig als wasmiddel voor oude textiel. De wortel als hoestmiddel is werk voor een apotheek; zelf bereiden geeft darmirritatie.",
"waterpeper":"Vers blad in kleine hoeveelheid als scherpe kruiderij. Als tinctuur traditioneel bij overvloedige menstruatie; niet tijdens zwangerschap.",
"robertskruid":"Thee van het verse kruid, 1 el per kop, 10 min; ook als mondspoeling. De geur maakt het geen keukenkruid.",
"pimpernel":"Jong blad rauw door salade of Frankfurter groene saus. Medicinaal als thee, 1 el per kop, samentrekkend.",
"nagelkruid":"Verse wortelstok in wijn, bier of stoofpot als kruidnagelvervanger. De geur vervliegt bij drogen, dus vers gebruiken.",
"stalkruid":"Wortelafkooksel, 1 tl per kop, 10 min koken, met ruim water erbij. Niet bij vochtophoping door hart- of nierfalen.",
"slangenkruid":"Alleen uitwendig als kompres. Inwendig gebruik is door de leveralkalo\u00efden afgeraden.",
"blauweknoop":"Wortelafkooksel, 1 tl per kop, 10 min koken. Groeit op beschermd nat hooiland \u2014 vrijwel altijd laten staan.",
"kaardebol":"Wortelafkooksel, 1 tl per kop. Geen vervanging van antibiotica bij een tekenbeet met ring; daarvoor naar de huisarts.",
"waterdrieblad":"Zeer bittere thee, een half theelepeltje per kop volstaat als bittermiddel voor de maaltijd.",
"zonnedauw":"Alleen uit gekweekt materiaal, als tinctuur of siroop bij kriebelhoest. In het wild streng beschermd.",
"knopighelmkruid":"Uitwendig als kompres of zalf bij zwellingen. Inwendig niet: het bevat hartglycosiden.",
"vlasbekje":"Uitwendig als zalf of kompres bij aambeien en zwellingen. Inwendig hooguit incidenteel als thee.",
"stokroos":"Bloemblaadjes koud trekken voor het slijm, 1 el per kop, 2 uur. Donkere rassen geven bovendien een diepe kleur.",
"grotepimpernel":"Wortel als afkooksel, 1 tl per kop, 10 min koken; sterk samentrekkend. Jong blad rauw als de kleine pimpernel.",
"ossentong":"Alleen uitwendig als kompres; de bloemen hooguit als garnering. Inwendig belasten de alkalo\u00efden de lever.",
"penningkruid":"Thee van het kruid, 1 el per kop, 10 min. Vooral uitwendig als wasing op slecht helende wondjes.",
"canadeseguldenroede":"Thee, 1 el per kop, 10 min, met ruim water erbij. Als plukken helpt tegen woekering is dat mooi meegenomen.",
"witteabeel":"Bast als afkooksel, 1 tl per kop; knoppen in vet getrokken tot zalf. Zelfde bezwaren als wilg.",
"grauwewilg":"Bast als afkooksel, 1 tl per kop, 10 min koken. Oogst spaarzaam en ring nooit een stam.",
"heelblaadjes":"Thee van het bloeiende kruid, 1 el per kop, 10 min; samentrekkend bij darmklachten.",
"kruisbladwalstro":"Thee 1 el per kop, of vers gekneusd als kompres, in dezelfde hoek als kleefkruid.",
"canadapopulier":"Knoppen in olie of vet trekken voor zalf; minder geurig dan de zwarte populier maar bruikbaar.",
"huislook":"Blad doorsnijden en het sap direct op de huid, als alo\u00eb. Inwendig in hoeveelheid braakverwekkend.",
"bergsteentijm":"Thee 1 tl per kop, afgedekt. In Nederland zeldzaam \u2014 alleen uit eigen tuin.",
"geelwalstro":"Thee 1 el per kop, 10 min; ook als stremsel bij het kaasmaken. Bevat cumarine, dus spaarzaam.",
"veenmos":"Alleen uitwendig, als wondverband \u2014 zoals in beide wereldoorlogen. Hoogveen is beschermd: niet oogsten.",
"lateguldenroede":"Als de andere guldenroeden: thee 1 el per kop, 10 min, met ruim water erbij.",
"grauweabeel":"Bast en knoppen als bij witte abeel: afkooksel of zalf, met dezelfde bezwaren als wilg.",
}

regels = "\n".join(' %-24s %s,' % (k+':', '"'+v.replace('"','\\"')+'"') for k, v in sorted(B.items()))
blok = ('/* Hoe verwerk je het? Op het blad stond wel waarv\u00f3\u00f3r een soort werd\n'
        '   gebruikt, maar niet hoe \u2014 en juist daar zit het verschil tussen werken\n'
        '   en niets doen. Koud trekken of koken, vers of gedroogd, uitwendig of\n'
        '   inwendig: dat bepaalt of er iets in je kopje zit. Waar alleen uitwendig\n'
        '   gebruik verantwoord is, staat dat er nadrukkelijk bij. */\nconst BEREIDING = {\n'
        + regels + '\n};\n\n')
s = rep(s, 'const STOF = {', blok + 'const STOF = {')
open(src, "w", encoding="utf-8").write(s)
print("bereidingen toegevoegd:", len(B))
