# -*- coding: utf-8 -*-
"""Gaea 0.57.0 — Engelse namen bij de soorten.
Als aparte tabel in plaats van een veld per soort: zo is hij in \u00e9\u00e9n oogopslag
na te lopen en aan te vullen. Waar geen gangbare Engelse naam bestaat \u2014 bij
een deel van de zwammen \u2014 blijft de regel weg; een verzonnen naam helpt
niemand die iets probeert op te zoeken."""
import sys
src = sys.argv[1] if len(sys.argv) > 1 else "index.html"
s = open(src, encoding="utf-8").read()

EN = {
# --- eetbare en medicinale kruiden ---
"daslook":"Ramsons / wild garlic","lookzonderlook":"Garlic mustard","zevenblad":"Ground elder",
"brandnetel":"Stinging nettle","kleinebrandnetel":"Small nettle","vogelmuur":"Chickweed",
"speenkruid":"Lesser celandine","hondsdraf":"Ground ivy","veldzuring":"Common sorrel",
"schapenzuring":"Sheep's sorrel","kleefkruid":"Cleavers","herderstasje":"Shepherd's purse",
"pinksterbloem":"Cuckooflower","veldkers":"Hairy bittercress","weegbree":"Ribwort plantain",
"groteweegbree":"Broadleaf plantain","madeliefje":"Daisy","paardenbloem":"Dandelion",
"kleinhoefblad":"Colt's foot","melkdistel":"Common sowthistle","akkerdistel":"Creeping thistle",
"klit":"Greater burdock","duizendblad":"Yarrow","brunel":"Selfheal","cichorei":"Chicory",
"bijvoet":"Mugwort","boerenwormkruid":"Tansy","heermoes":"Field horsetail",
"sintjanskruid":"St John's wort","kamille":"German chamomile","moerasspirea":"Meadowsweet",
"valeriaan":"Valerian","marjolein":"Oregano / wild marjoram","tijm":"Large thyme",
"melisse":"Lemon balm","watermunt":"Water mint","waterkers":"Watercress",
"kaasjeskruid":"Common mallow","heemst":"Marshmallow","smeerwortel":"Comfrey",
"stinkendegouwe":"Greater celandine","zeekraal":"Glasswort / samphire","lamsoor":"Sea lavender",
"strandmelde":"Spear-leaved orache","melganzenvoet":"Fat hen","postelein":"Purslane",
"kraailook":"Crow garlic","agrimonie":"Agrimony","engelwortel":"Garden angelica","hop":"Hop",
"japanseduizendknoop":"Japanese knotweed",
# --- struiken en bomen ---
"vlier":"Elder","sleedoorn":"Blackthorn / sloe","meidoorn":"Hawthorn","hondsroos":"Dog rose",
"rimpelroos":"Japanese rose","braam":"Bramble / blackberry","framboos":"Raspberry",
"bosbes":"Bilberry","duindoorn":"Sea buckthorn","lijsterbes":"Rowan",
"gelderseroos":"Guelder rose","hazelaar":"Hazel","walnoot":"Walnut","tammekastanje":"Sweet chestnut",
"beuk":"Beech","eik":"Pedunculate oak","linde":"Large-leaved lime","berk":"Silver birch",
"grovden":"Scots pine","fijnspar":"Norway spruce","douglas":"Douglas fir",
"amerikaansevogelkers":"Black cherry","mispel":"Medlar","kruidvlier":"Dwarf elder",
# --- giftig ---
"scheerling":"Poison hemlock","watertorkruid":"Hemlock water dropwort","hondspeterselie":"Fool's parsley",
"herfsttijloos":"Autumn crocus / meadow saffron","lelietje":"Lily of the valley",
"aronskelk":"Lords and ladies","reuzenberenklauw":"Giant hogweed","vingerhoedskruid":"Foxglove",
"wolfskers":"Deadly nightshade","monnikskap":"Monkshood","taxus":"Yew","doornappel":"Thorn apple",
"bilzekruid":"Henbane","zwartenachtschade":"Black nightshade","salomonszegel":"Solomon's seal",
"fluitenkruid":"Cow parsley","berenklauw":"Hogweed","wildepeen":"Wild carrot","pastinaak":"Wild parsnip",
# --- zwammen ---
"morielje":"Morel","eekhoorntjesbrood":"Penny bun / cep","kastanjeboleet":"Bay bolete",
"cantharel":"Chanterelle","stekelzwam":"Hedgehog mushroom","parasolzwam":"Parasol mushroom",
"weidechampignon":"Field mushroom","zwavelzwam":"Chicken of the woods","biefstukzwam":"Beefsteak fungus",
"judasoor":"Wood ear","fluweelpootje":"Velvet shank","oesterzwam":"Oyster mushroom",
"reuzenbovist":"Giant puffball","paarseschijnridder":"Wood blewit","berkenzwam":"Birch polypore",
"elfenbankje":"Turkeytail","tonderzwam":"Tinder fungus","groeneknolamaniet":"Death cap",
"witteknolamaniet":"Destroying angel","panteramaniet":"Panther cap","vliegenzwam":"Fly agaric",
"satansboleet":"Devil's bolete","krulzoom":"Brown roll-rim","weidetrechterzwam":"Fool's funnel",
"bundelmosklokje":"Funeral bell","gewonezwavelkop":"Sulphur tuft","kaleinktzwam":"Common inkcap",
"geleknolamaniet":"False death cap",
# --- tuin en keuken ---
"winterpostelein":"Miner's lettuce","veldsla":"Lamb's lettuce","dovenetel":"White deadnettle",
"paarsedovenetel":"Red deadnettle","raket":"Hedge mustard","klaproos":"Common poppy",
"rodeklaver":"Red clover","zilverschoon":"Silverweed","tormentil":"Tormentil",
"bosaardbei":"Wild strawberry","lisdodde":"Bulrush / cattail","aardaker":"Tuberous pea",
"teunisbloem":"Evening primrose","viooltje3":"Heartsease","maartsviooltje":"Sweet violet",
"sleutelbloem":"Cowslip","koningskaars":"Great mullein","klimop":"Ivy","jeneverbes":"Juniper",
"gagel":"Bog myrtle","kalmoes":"Sweet flag","zeeaster":"Sea aster","strandbiet":"Sea beet",
"zeesla":"Sea lettuce","blaaswier":"Bladderwrack","suikerwier":"Sugar kelp","wilg":"White willow",
"krent":"Juneberry","zwartebes":"Blackcurrant","kruisbes":"Gooseberry","iep":"Field elm",
"esdoorn":"Sycamore","robinia":"Black locust","zoetekers":"Wild cherry","vogelkers":"Bird cherry",
"gouderegen":"Laburnum","kardinaalsmuts":"Spindle","hulst":"Holly","sneeuwbes":"Snowberry",
"heggenrank":"White bryony","bosrank":"Old man's beard","gelelis":"Yellow flag iris",
"berkenboleet":"Birch bolete","stobbezwam":"Sheathed woodtuft","weidekringzwam":"Fairy ring champignon",
"parelamaniet":"Blusher","hertenzwam":"Deer shield","kluifzwam":"False morel",
"gordijnzwam":"Webcaps","valsehanenkam":"False chanterelle","karbolchampignon":"Yellow stainer",
"aardappelbovist":"Common earthball","braakrussula":"The sickener","lakzwam":"Reishi",
"salie":"Sage","rozemarijn":"Rosemary","lavendel":"Lavender","echtetijm":"Common thyme",
"basilicum":"Basil","peterselie":"Parsley","bieslook":"Chives","dille":"Dill","venkel":"Fennel",
"koriander":"Coriander / cilantro","dragon":"Tarragon","kervel":"Chervil","bonenkruid":"Summer savory",
"laurier":"Bay laurel","pepermunt":"Peppermint","citroenverbena":"Lemon verbena",
"goudsbloem":"Pot marigold","echinacea":"Purple coneflower","hysop":"Hyssop","lavas":"Lovage",
"alsem":"Wormwood","knoflook":"Garlic","mierikswortel":"Horseradish","zoethout":"Liquorice",
"gember":"Ginger","kurkuma":"Turmeric","kaneel":"Cinnamon","anijs":"Anise","karwij":"Caraway",
"roomsekamille":"Roman chamomile","passiebloem":"Passionflower","vrouwenmantel":"Lady's mantle",
"guldenroede":"Goldenrod","berendruif":"Bearberry","selderij":"Wild celery","citroengras":"Lemongrass",
"ginkgo":"Ginkgo","wijnruit":"Rue","aloe":"Aloe vera","munt":"Spearmint","komijn":"Cumin",
"nigella":"Black cumin","veldsalie":"Meadow clary","scharlei":"Clary sage","ananassalie":"Pineapple sage",
"kattenkruid":"Catnip","tulsi":"Holy basil","bernagie":"Borage","oostindischekers":"Nasturtium",
"mariadistel":"Milk thistle","duivelsklauw":"Devil's claw","kruidnagel":"Clove","kardemom":"Cardamom",
"wildetijm":"Wild thyme","zenegroen":"Bugle","ereprijs":"Heath speedwell","knoopkruid":"Brown knapweed",
"kattenstaart":"Purple loosestrife","zwartemosterd":"Black mustard","biggenkruid":"Cat's ear",
"reuklozekamille":"Scentless mayweed","schijfkamille":"Pineappleweed","hennepnetel":"Common hemp-nettle",
"grotebevernel":"Greater burnet-saxifrage","slaapbol":"Opium poppy","jacobskruiskruid":"Ragwort",
"bitterzoet":"Bittersweet nightshade","lidrus":"Marsh horsetail","tuinwolfsmelk":"Petty spurge",
"narcis":"Wild daffodil","sneeuwklokje":"Snowdrop","paardenkastanje":"Horse chestnut",
"peperboompje":"Mezereon","nevelzwam":"Clouded funnel","anijschampignon":"Horse mushroom",
"galboleet":"Bitter bolete","kapjesmorielje":"Early morel","oorlepelzwam":"Earpick fungus",
"wederik":"Yellow loosestrife","rodebosbes":"Lingonberry","wilgenroosje":"Rosebay willowherb",
"koekoeksbloem":"Ragged robin","hengel":"Wood cow-wheat","margriet":"Oxeye daisy",
"bosengelwortel":"Wild angelica","bospaardenstaart":"Wood horsetail","grofplaatrussula":"Blackening brittlegill",
"zwartpurperenrussula":"Purple brittlegill","geelwitterussula":"Ochre brittlegill",
"sponszwam":"Cauliflower fungus","honingzwam":"Honey fungus","grauweridderzwam":"Charbonnier",
"zwavelridderzwam":"Sulphur knight","oranjerodegordijnzwam":"Fool's webcap",
"schubbigebundelzwam":"Shaggy scalycap","roodbruineamaniet":"Tawny grisette",
"smakelijkemelkzwam":"Saffron milkcap","wolligemelkzwam":"Woolly milkcap","peperigemelkzwam":"Peppery milkcap",
"bruineringboleet":"Slippery jack","koeienboleet":"Bovine bolete","peperboleet":"Peppery bolete",
"heksenboleet":"Scarletina bolete","fluweelboleet":"Red cracking bolete","eikhaas":"Hen of the woods / maitake",
"reuzenzwam":"Giant polypore","plattetonderzwam":"Artist's bracket","chaga":"Chaga",
"schaapszwam":"Sheep polypore","parelstuifzwam":"Common puffball","zwartetrompet":"Horn of plenty",
"geletrompet":"Yellowfoot / winter chanterelle","grotestinkzwam":"Stinkhorn","geletrilzwam":"Yellow brain",
"geknobbeldevezelkop":"Split fibrecap","wittevezelkop":"White fibrecap","grotesatijnzwam":"Livid pinkgill",
"molenaar":"The miller","geschubdeinktzwam":"Shaggy inkcap","glimmerinktzwam":"Glistening inkcap",
"zilversteelchampignon":"Wood mushroom","knolparasolzwam":"Shaggy parasol","vuurzwammetje":"Blackening waxcap",
"grotebloedsteelmycena":"Burgundydrop bonnet","waaiertje":"Splitgill","pruikzwam":"Lion's mane",
"koraalzwam":"Yellow coral","witkoraaltje":"Crested coral","rodekelkzwam":"Scarlet elfcup",
"oranjebekerzwam":"Orange peel fungus","bisschopsmuts":"Elfin saddle","beukenrussula":"Beechwood sickener",
"grotetrechterzwam":"Trooping funnel","rookzwavelkop":"Conifer tuft","paarsesteelschijnridder":"Field blewit",
"zwartgroenerussula":"Powdery brittlegill","valsjudasoor":"Tripe fungus","roodrandhoutzwam":"Red-belted bracket",
"zadelzwam":"Dryad's saddle","gewoneaardster":"Collared earthstar","loodgrijzebovist":"Grey puffball",
"vroegeakkerzwam":"Spring fieldcap","grotebreeksteelmycena":"Pale brittlestem","gezoneerdevlekplaat":"Brown mottlegill",
"radijsvaalhoed":"Poisonpie","gewonefopzwam":"Deceiver","amethistzwam":"Amethyst deceiver",
"elzenkorstzwam":"Hairy curtain crust","zwartetrilzwam":"Witches' butter","geelhoorntje":"Yellow stagshorn",
"grijzebuisjeszwam":"Smoky bracket","dennenvoetzwam":"Dyer's mazegill","paarsedennenzwam":"Purplepore bracket",
"geweizwam":"Candlesnuff fungus","koperrodespijkerzwam":"Copper spike","schubbigestekelzwam":"Scaly tooth",
"dennenkegelzwam":"Pinecone cap","scherpelfenbankje":"Bitter oysterling","reuzenknotszwam":"Giant club",
"kleinestinkzwam":"Dog stinkhorn","kammosselrussula":"Crab brittlegill","grotetolzwam":"Velvet rollrim",
"saffraanmycena":"Saffrondrop bonnet","zomertruffel":"Summer truffle","hertentruffel":"Deer truffle",
"wortelvrucht":"Yellow false truffle","blaasjeszwam":"Blistered cup","eikelbekerzwam":"Hare's ear",
"wimperzwam":"Common eyelash","zwartekelkzwam":"Black bulgar","kopergroenbeker":"Green elfcup",
"kogelhoutskoolzwam":"King Alfred's cakes","doolhofzwam":"Oak mazegill","fopelfenbankje":"Birch mazegill",
"zomerhoutzwam":"Conifer blueing bracket","echtetolzwam":"Tiger's eye","oranjeaderzwam":"Wrinkled crust",
"kleineknolparasol":"Deadly dapperling","beukwortelzwam":"Rooting shank","breedplaatzwam":"Whitelaced shank",
"schijntrechterzwam":"The goblet","populierleemhoed":"Poplar fieldcap / pioppino",
"draadknotszwam":"Pipe club","narcismosklokje":"Orange mosscap","plooivoetstuifzwam":"Meadow puffball",
"korrelhoed":"Earthy powdercap","slijmigespijkerzwam":"Slimy spike","kopergroenekopspijker":"Verdigris agaric",
"somberehoningzwam":"Dark honey fungus","beukenzwam":"Beech mushroom / shimeji",
# --- bomen en struiken, tweede lichting ---
"grauweels":"Grey alder","veldesdoorn":"Field maple","zwartels":"Black alder","haagbeuk":"Hornbeam",
"es":"Ash","ratelpopulier":"Aspen","boswilg":"Goat willow","zwartepopulier":"Black poplar",
"rodekornoelje":"Common dogwood","gelekornoelje":"Cornelian cherry","vuilboom":"Alder buckthorn",
"wegedoorn":"Purging buckthorn","gewoneliguster":"Wild privet","kamperfoelie":"Honeysuckle",
"zuurbes":"Barberry","mahonie":"Oregon grape","appelbes":"Black chokeberry","dwergmispel":"Wild cotoneaster",
"kweepeer":"Quince","moerbei":"Black mulberry","lariks":"European larch","zilverspar":"Silver fir",
"westerselevensboom":"White cedar","struikhei":"Heather / ling","dophei":"Cross-leaved heath",
"kraaihei":"Crowberry","brem":"Broom","gaspeldoorn":"Gorse","olijfwilg":"Autumn olive",
"wildewingerd":"Virginia creeper","hemelboom":"Tree of heaven","gewoneplataan":"London plane","buxus":"Box",
# --- tuin ---
"dropplant":"Anise hyssop","bergamotplant":"Bee balm / bergamot","shiso":"Shiso / perilla",
"rucola":"Rocket / arugula","tuinkers":"Garden cress","fenegriek":"Fenugreek","stevia":"Stevia",
"arnica":"Arnica","alant":"Elecampane","honingklaver":"Yellow sweet clover","vlas":"Flax / linseed",
"ijzerhard":"Vervain","daglelie":"Orange daylily","hosta":"Hosta","afrikaantje":"French marigold",
"ananaskers":"Cape gooseberry","pompoen":"Pumpkin","saffraankrokus":"Saffron crocus",
"wonderboom":"Castor bean","oleander":"Oleander","akelei":"Columbine","kerstroos":"Christmas rose",
"longkruid":"Lungwort",
# --- kruiden, latere lichtingen ---
"waterscheerling":"Cowbane","kleinewatereppe":"Lesser water-parsnip","grotewatereppe":"Greater water-parsnip",
"roomsekervel":"Sweet cicely","dollekervel":"Rough chervil","zwartmoeskervel":"Alexanders",
"aardkastanje":"Pignut","melkeppe":"Milk parsley","heggendoornzaad":"Upright hedge-parsley",
"barbarakruid":"Winter cress","gelewaterkers":"Great yellow-cress","lepelblad":"Common scurvygrass",
"zeeraket":"Sea rocket","judaspenning":"Honesty","kompassla":"Prickly lettuce","akkerkool":"Nipplewort",
"morgenster":"Goat's beard","muizenoor":"Mouse-ear hawkweed","speerdistel":"Spear thistle",
"kruldistel":"Welted thistle","koninginnekruid":"Hemp agrimony","groothoefblad":"Butterbur",
"tandzaad":"Trifid bur-marigold","scherpeboterbloem":"Meadow buttercup","dotterbloem":"Marsh marigold",
"bosanemoon":"Wood anemone","moerasandoorn":"Marsh woundwort","bosandoorn":"Hedge woundwort",
"wolfspoot":"Gypsywort","blauwglidkruid":"Common skullcap","malrove":"White horehound",
"stinkendeballote":"Black horehound","borstelkrans":"Wild basil","gamander":"Wood sage",
"dagkoekoeksbloem":"Red campion","zeepkruid":"Soapwort","perzikkruid":"Redshank",
"waterpeper":"Water pepper","zwaluwtong":"Black bindweed","klaverzuring":"Wood sorrel",
"robertskruid":"Herb Robert","reigersbek":"Common stork's-bill","springbalsemien":"Touch-me-not balsam",
"muurpeper":"Biting stonecrop","pimpernel":"Salad burnet","nagelkruid":"Wood avens",
"rolklaver":"Bird's-foot trefoil","stalkruid":"Common restharrow","waterweegbree":"Water plantain",
"geleplomp":"Yellow water-lily","riet":"Common reed","liesgras":"Reed sweet-grass",
"engelsgras":"Thrift","schorrenkruid":"Annual seablite","zeeweegbree":"Sea plantain",
"slangenkruid":"Viper's bugloss","vergeetmijnietje":"Water forget-me-not","veldhondstong":"Hound's tongue",
"grasklokje":"Harebell","beemdkroon":"Field scabious","blauweknoop":"Devil's-bit scabious",
"kaardebol":"Teasel","haagwinde":"Hedge bindweed","akkerwinde":"Field bindweed",
"boshyacint":"Bluebell","vogelmelk":"Star-of-Bethlehem","eenbes":"Herb Paris",
"maagdenpalm":"Lesser periwinkle","mansoor":"Asarabacca","kleinkruiskruid":"Groundsel",
"muursla":"Wall lettuce","heggenwikke":"Tufted vetch","melkkruid":"Sea milkwort",
"waterdrieblad":"Bogbean","zonnedauw":"Round-leaved sundew","knopighelmkruid":"Common figwort",
"vlasbekje":"Common toadflax","amarant":"Redroot amaranth","stokroos":"Hollyhock",
"grotepimpernel":"Great burnet","ossentong":"Common bugloss","ridderspoor":"Forking larkspur",
"lenteklokje":"Spring snowflake","penningkruid":"Creeping jenny","zeekool":"Sea kale",
"reukelozekamille":"Sea mayweed","canadeseguldenroede":"Canadian goldenrod","grotecentaurie":"Greater knapweed",
"koolzaad":"Oilseed rape","wittewaterlelie":"White water-lily","pijlkruid":"Arrowhead",
"hemelsleutel":"Orpine","witvetkruid":"White stonecrop","witteabeel":"White poplar",
"grauwewilg":"Grey willow","noorseesdoorn":"Norway maple","amerikaanseeik":"Red oak",
"vuurdoorn":"Firethorn","geleridderzwam":"Yellow knight","zeepridderzwam":"Soapy knight",
"galrussula":"Geranium brittlegill","zoetmelkzwam":"Mild milkcap","grijzeslankeamaniet":"Grisette",
"kammetjesstekelzwam":"Coral tooth","aalbes":"Redcurrant","kleinstreepzaad":"Smooth hawk's-beard",
"heelblaadjes":"Common fleabane","kruisbladwalstro":"Crosswort","blauwwalstro":"Field madder",
"watergentiaan":"Fringed water-lily","juffertje":"Love-in-a-mist","schijnaardbei":"Mock strawberry",
"puntwederik":"Dotted loosestrife","stinkendnieskruid":"Stinking hellebore","schijncipres":"Lawson cypress",
"japansesierkwee":"Japanese quince","wittemoerbei":"White mulberry","canadapopulier":"Hybrid black poplar",
"zurekers":"Sour cherry","rodekamperfoelie":"Fly honeysuckle","wijnstok":"Grapevine",
"zonnebloem":"Sunflower","courgette":"Courgette / zucchini","lampionplant":"Chinese lantern",
"geleanemoon":"Yellow anemone","blaartrekkendeboterbloem":"Celery-leaved buttercup",
"zwarttandzaad":"Beggarticks","voorjaarspronkridder":"St George's mushroom","tijgerridderzwam":"Tiger knight",
"goudvliesbundelzwam":"Golden scalycap","elfenschermpje":"Common bonnet","wittesatijnvezelkop":"Lilac fibrecap",
"grotebekerzwam":"Bay cup","houtknotszwam":"Dead man's fingers","eikensponszwam":"Oak cauliflower",
"gelezwavelporiezwam":"Bitter sheep polypore","oranjedruppelzwam":"Common jellyspot",
"gelehersenzwam":"Brain jelly","keizersamaniet":"Caesar's mushroom","blaassilene":"Bladder campion",
"muurleeuwenbek":"Ivy-leaved toadflax","rodebes":"Redcurrant","huislook":"Houseleek",
"herik":"Charlock","raapzaad":"Wild turnip","avondkoekoeksbloem":"White campion",
"bergsteentijm":"Wood calamint","geelwalstro":"Lady's bedstraw","duifkruid":"Small scabious",
"rapunzelklokje":"Rampion bellflower","ruigklokje":"Nettle-leaved bellflower","leeuwenbek":"Snapdragon",
"tuinridderspoor":"Delphinium","spaansehyacint":"Spanish bluebell","welriekendesalomonszegel":"Angular Solomon's seal",
"kleinezonnedauw":"Oblong-leaved sundew","veenmos":"Sphagnum moss","boszwenkgras":"Giant fescue",
"boskruiskruid":"Heath groundsel","lateguldenroede":"Giant goldenrod","kleinspringzaad":"Small balsam",
"reuzenbalsemien":"Himalayan balsam","zachteooievaarsbek":"Dovesfoot crane's-bill",
"zachteduizendknoop":"Tasteless water-pepper","voederwikke":"Common vetch",
"akkervergeetmijnietje":"Field forget-me-not","grauweabeel":"Grey poplar","wintereik":"Sessile oak",
"aardpeer":"Jerusalem artichoke","scherpegroenerussula":"Green brittlegill",
"wittesatijnzwam":"Silky pinkgill","grotemaagdenpalm":"Greater periwinkle",
}

regels = "\n".join(' %-26s %s,' % (k+':', '"'+v.replace('"','\\"')+'"') for k, v in sorted(EN.items()))
blok = ('/* Engelse namen. Veel van wat je online over een soort vindt staat in het\n'
        '   Engels; met deze naam weet je waarnaar je zoekt. Waar geen gangbare\n'
        '   Engelse naam bestaat blijft de regel weg \u2014 een verzonnen naam stuurt\n'
        '   je alleen maar het verkeerde spoor op. */\nconst EN = {\n' + regels + '\n};\n\n')

anker = 'const STOF = {'
assert s.count(anker) == 1
s = s.replace(anker, blok + anker)
open(src, "w", encoding="utf-8").write(s)
print("Engelse namen toegevoegd:", len(EN))
