# -*- coding: utf-8 -*-
"""Gaea 0.65.0 — werkzame stof bij de laatste 102 medicinale soorten."""
import sys
src = sys.argv[1] if len(sys.argv) > 1 else "index.html"
s = open(src, encoding="utf-8").read()
def rep(hay, old, new, n=1):
    c = hay.count(old); assert c == n, f"{c}x: {old[:80]!r}"
    return hay.replace(old, new)

N = {
"vogelmuur":("Saponinen en vitamine C","saponinen","De saponinen verklaren het verzachtende gebruik op de huid; het blad is daarnaast rijk aan vitamine C."),
"hondsdraf":("Rosmarinuszuur","fenolzuren","Ontstekingsremmend, en samen met de bitterstoffen de reden voor het oude gebruik bij vastzittend slijm."),
"kleefkruid":("Asperulosiden","irido\u00efden","Breken bij verhitting af \u2014 vandaar dat kleefkruid koud wordt getrokken."),
"herderstasje":("Peptiden en flavono\u00efden","peptiden","Werken samentrekkend op de baarmoeder; ze vervallen snel bij drogen, wat verklaart waarom vers materiaal veel sterker is."),
"groteweegbree":("Aucubine en slijmstoffen","irido\u00efden","Aucubine werkt bacterieremmend; het slijm verzacht de keel."),
"madeliefje":("Saponinen en polyacetylenen","saponinen","Mild ontstekingsremmend; dezelfde hoek als de veel sterkere arnica, maar zonder de bezwaren."),
"kleinhoefblad":("Slijmstoffen en pyrrolizidine-alkalo\u00efden","polysachariden","Het slijm verzacht de hoest, de alkalo\u00efden belasten de lever \u2014 vandaar het strikt kortdurende gebruik."),
"klit":("Inuline en polyacetylenen","polysachariden","Inuline maakt de wortel zoetig en voedt de darmflora; de polyacetylenen werken bacterieremmend."),
"brunel":("Rosmarinuszuur en looistoffen","fenolzuren","Samentrekkend en virusremmend; de reden voor het gorgelen bij keelpijn."),
"bijvoet":("Thujon en bitterstoffen","terpenen","Thujon prikkelt in hoeveelheid het zenuwstelsel; de bitterstoffen verklaren het gebruik bij vet vlees."),
"boerenwormkruid":("Thujon","terpenen","Werkt op insecten en op het zenuwstelsel; genoeg om motten te weren, te veel om te drinken."),
"moerasspirea":("Salicylaldehyde","fenolglycosiden","De voorloper van aspirine \u2014 de stofnaam komt van Spiraea, de oude naam van deze plant."),
"marjolein":("Carvacrol","fenolen","Bacterieremmend en krampstillend; vervliegt bij lang koken, dus laat toevoegen."),
"tijm":("Thymol en carvacrol","fenolen","Sterk bacterieremmend en slijmoplossend; de reden dat tijm het klassieke hoestkruid is."),
"melisse":("Citral en rosmarinuszuur","terpenen","Citral geeft de citroengeur en vervliegt snel bij drogen; rosmarinuszuur remt het koortslipvirus."),
"watermunt":("Menthol en pulegon","terpenen","Meer pulegon dan pepermunt, wat hem scherper maakt en de reden is om spaarzaam te doseren."),
"stinkendegouwe":("Chelidonine","alkalo\u00efden","Het oranje sap is krampstillend maar levertoxisch bij inname; uitsluitend uitwendig, druppel voor druppel."),
"agrimonie":("Looistoffen en agrimoniine","tannines","Sterk samentrekkend op slijmvlies; vandaar de gorgeldrank en het wondkompres."),
"engelwortel":("Furocumarinen en angelicine","cumarinen","Bitter en krampstillend, maar ze maken de huid lichtgevoelig \u2014 oogst met bedekte armen."),
"braam":("Looistoffen","tannines","Trekken het darmslijmvlies samen, wat de werking bij diarree verklaart. De rijpe bes bevat ze nauwelijks."),
"framboos":("Fragarine en looistoffen","tannines","Fragarine ontspant of verstevigt de baarmoederspier afhankelijk van de fase; daar komt het gebruik aan het eind van een zwangerschap vandaan."),
"bosbes":("Anthocyanen en looistoffen","flavono\u00efden","Gedroogd overheersen de looistoffen, wat stopt; vers overheerst het vruchtvocht, wat juist doorlaat."),
"linde":("Slijmstoffen en farnesol","polysachariden","Farnesol geeft de honinggeur; het slijm verzacht de keel en het geheel werkt zweetdrijvend."),
"grovden":("Alfa-pineen","terpenen","Slijmoplossend en licht ontsmettend op de luchtwegen; de stof achter de dennengeur."),
"judasoor":("Polysachariden","polysachariden","Onderzocht op bloedstolling; in Chinese bereidingen daarom een vaste zwam bij vaatklachten."),
"berkenzwam":("Betuline en polyporeenzuur","triterpenen","Betuline haalt de zwam uit de berkenbast; polyporeenzuur is bacterieremmend, wat het oude gebruik als wondverband verklaart."),
"dovenetel":("Slijmstoffen en flavono\u00efden","polysachariden","Verzachtend op slijmvlies; anders dan de brandnetel bevat de dovenetel geen brandharen en geen histamine."),
"raket":("Glucosinolaten","glucosinolaten","Scherpe mosterdolie die de luchtwegen prikkelt en zo het slijm losmaakt \u2014 vandaar de naam zangerskruid."),
"klaproos":("Rhoeadine","alkalo\u00efden","Mild kalmerend, niet verwant aan de morfine van de slaapbol; de bloemblaadjes zijn onschuldig."),
"rodeklaver":("Formononetine en biochanine","iso-flavonen","Plantaardige oestrogenen; daarom niet gebruiken bij hormoongevoelige aandoeningen."),
"zilverschoon":("Looistoffen","tannines","Sterk samentrekkend; het zilverachtige blad werd juist daarom als kompres gebruikt."),
"tormentil":("Tormentol en catechinelooistoffen","tannines","Een van de looistofrijkste wortels van onze flora \u2014 de reden voor het gebruik als mondspoeling."),
"bosaardbei":("Looistoffen en vitamine C","tannines","Het blad is samentrekkend, de vrucht juist verfrissend; twee verschillende toepassingen van \u00e9\u00e9n plant."),
"viooltje3":("Saponinen en salicylverbindingen","saponinen","Slijmoplossend bij droge hoest; het viooltje werd daarom in hoestthee gemengd."),
"maartsviooltje":("Saponinen en violine","saponinen","In het blad mild, in de wortel zo sterk dat die braakverwekkend werkt \u2014 die blijft dus buiten de thee."),
"sleutelbloem":("Primulasaponinen","saponinen","Maken vastzittend slijm dunner; ze zitten vooral in de wortel, veel minder in de bloem."),
"koningskaars":("Slijmstoffen en verbascosaponinen","polysachariden","Het slijm verzacht, de saponinen maken los. De haartjes moeten eruit gezeefd: die prikkelen de keel."),
"klimop":("Hederasaponinen","saponinen","Krampstillend op de luchtwegen in gestandaardiseerde vorm, maar prikkelend voor huid en maag in ruw materiaal."),
"jeneverbes":("Terpineol-4","terpenen","Waterafdrijvend via de nier; bij langdurig gebruik prikkelt het het nierweefsel, vandaar de beperkte duur."),
"kalmoes":("Asaron en bitterstoffen","fenylpropanen","De bitterstoffen wekken de eetlust; asaron is de reden om alleen de Europese vorm en kortdurend te gebruiken."),
"blaaswier":("Jodium en alginaten","mineralen","Het jodiumgehalte is hoog en wisselt sterk \u2014 daarom niet bij schildklierklachten."),
"zwartebes":("Anthocyanen en gamma-linoleenzuur","flavono\u00efden","De bes voor de vaatwand, het blad voor de vochtafdrijving \u2014 verschillende stoffen, verschillend gebruik."),
"lakzwam":("Ganoderzuren en b\u00e8ta-glucanen","triterpenen","De ganoderzuren geven de bittere smaak en lossen in alcohol op; de glucanen juist in water. Vandaar het dubbele aftreksel."),
"peterselie":("Apiol en myristicine","fenylpropanen","Waterafdrijvend, maar in medicinale hoeveelheid werkt apiol op de baarmoeder \u2014 niet tijdens zwangerschap."),
"bonenkruid":("Carvacrol","fenolen","Bacterieremmend en krampstillend; dempt de winderigheid van peulvruchten, waar de naam vandaan komt."),
"citroenverbena":("Citral en verbascoside","terpenen","Citral geeft de geur en houdt bij drogen uitzonderlijk goed stand, anders dan bij melisse."),
"hysop":("Pinocamfon","terpenen","Slijmoplossend, maar in hoge dosis prikkelend voor het zenuwstelsel \u2014 vandaar spaarzaam gebruik."),
"roomsekamille":("Angelicazuuresters","terpenen","Sterker en bitterder dan echte kamille; dezelfde krampstillende werking maar in kleinere hoeveelheid nodig."),
"citroengras":("Citral","terpenen","Zelfde stof als in melisse; geeft de citroengeur en werkt bacterieremmend en insectenwerend."),
"wijnruit":("Rutine en furocumarinen","flavono\u00efden","Rutine versterkt de vaatwand; de furocumarinen maken de huid sterk lichtgevoelig."),
"munt":("Carvon","terpenen","Anders dan pepermunt, die menthol bevat: carvon geeft de zachtere smaak en werkt milder op de maag."),
"komijn":("Cuminaldehyde","terpenen","Verteringsbevorderend; de stof achter de kenmerkende geur van geroosterd komijnzaad."),
"nigella":("Thymochinon","chinonen","Ontstekingsremmend en onderzocht op afweer; de stof waarop het meeste onderzoek naar zwarte komijn zich richt."),
"veldsalie":("Thujon en rosmarinuszuur","terpenen","Minder thujon dan echte salie, wat hem milder maakt maar ook zwakker."),
"scharlei":("Linalylacetaat en sclareol","terpenen","Sclareol is de basis van veel parfums; het zaadslijm werd uitwendig bij een geprikkeld oog gebruikt."),
"kattenkruid":("Nepetalacton","terpenen","Werkt op katten via de reuk en op mensen mild kalmerend via de thee; verdwijnt bij koken."),
"tulsi":("Eugenol en ursolzuur","fenolen","Eugenol als in kruidnagel; in de ayurveda geldt tulsi als aanpassingskruid bij spanning."),
"oostindischekers":("Benzylisothiocyanaat","glucosinolaten","Sterk bacterieremmend, ook in de blaas; komt alleen rauw vrij, verhitting breekt het af."),
"kardemom":("Cineol en terpinylacetaat","terpenen","Verteringsbevorderend en de reden dat kardemom bij koffie wordt gedaan."),
"wildetijm":("Thymol en carvacrol","fenolen","Zelfde stoffen als echte tijm maar in lagere concentratie \u2014 milder, en daarom geschikt als badkruid."),
"zenegroen":("Irido\u00efden en looistoffen","irido\u00efden","Samentrekkend en licht ontstekingsremmend; de basis van het gebruik als wondkruid."),
"ereprijs":("Aucubine en catalpol","irido\u00efden","Bitter en licht ontstekingsremmend; verklaart het gebruik als dagelijkse thee in vroeger Europa."),
"knoopkruid":("Cnicine en looistoffen","sesquiterpeenlactonen","Bitter en samentrekkend; verwant aan de bitterstof van de gezegende distel."),
"kattenstaart":("Salicarine en looistoffen","tannines","Zeer looistofrijk \u2014 vandaar de betrouwbare werking bij diarree en als spoeling."),
"grotebevernel":("Pimpinelline en saponinen","cumarinen","Slijmoplossend en krampstillend; de wortel is veel sterker dan het blad."),
"paardenkastanje":("Aescine","saponinen","Verstevigt de vaatwand en remt vochtlekkage \u2014 de basis van alle middelen bij zware benen. Ruw zaad is giftig."),
"rodebosbes":("Arbutine en anthocyanen","fenolglycosiden","Arbutine als in beredruif, in lagere concentratie: milder maar met dezelfde beperkte gebruiksduur."),
"wilgenroosje":("Oenotheine B en looistoffen","tannines","Onderzocht bij prostaatklachten; het gefermenteerde blad verliest een deel van de scherpte."),
"margriet":("Sesquiterpeenlactonen","sesquiterpeenlactonen","Mild krampstillend, in dezelfde familie als kamille maar zwakker."),
"bosengelwortel":("Furocumarinen en angelicazuur","cumarinen","Als bij de grote engelwortel: bitter en krampstillend, met dezelfde lichtgevoeligheid van de huid."),
"bospaardenstaart":("Kiezelzuur","mineralen","Zit vastgelegd in de celwand en komt pas na lang koken vrij \u2014 trekken alleen levert niets op."),
"sponszwam":("B\u00e8ta-glucanen","b\u00e8ta-glucanen","Zoals bij de meeste eetbare zwammen; de voedingswaarde is hier belangrijker dan een aftreksel."),
"beukenzwam":("B\u00e8ta-glucanen en hypsin","b\u00e8ta-glucanen","In Japan onderzocht op afweer en cholesterol; laboratoriumwerk, geen bewezen behandeling."),
"zwartels":("Ellagitannines","tannines","Sterk samentrekkend; verklaart het uitwendige gebruik en waarom de bast inwendig misselijk maakt."),
"es":("Fraxine en mannitol","cumarinen","Mannitol werd als manna gewonnen: een zacht laxeermiddel en suikervervanger."),
"ratelpopulier":("Salicine en populine","fenolglycosiden","Het lichaam zet salicine om in salicylzuur, dezelfde weg als bij wilg en aspirine."),
"boswilg":("Salicine","fenolglycosiden","Dezelfde stof als bij de schietwilg; de bast van jonge takken bevat er het meeste van."),
"zwartepopulier":("Salicine en balsemharsen","fenolglycosiden","De harsen geven de zalf zijn geur en kleefkracht, de salicine de pijnstillende werking."),
"vuilboom":("Glucofranguline","anthrachinonen","Vers prikkelt het hevig; pas na een jaar drogen ontstaat de mildere vorm die als laxeermiddel bruikbaar is."),
"zuurbes":("Berberine","alkalo\u00efden","Kleurt hout en bast geel. Remt leverenzymen, dus slecht te combineren met veel medicijnen."),
"appelbes":("Anthocyanen","flavono\u00efden","Een van de hoogste gehaltes van alle vruchten; ze geven de kleur en de droge mond."),
"moerbei":("1-Deoxynojirimycine","alkalo\u00efden","Remt in het blad het enzym dat suikers afbreekt \u2014 daar komt het onderzoek naar bloedsuiker vandaan."),
"lariks":("Arabinogalactaan","polysachariden","Een oplosbare vezel uit het hout, onderzocht als prebioticum; de hars levert Venetiaanse terpentijn."),
"zilverspar":("Bornylacetaat","terpenen","Geeft de frisse naaldgeur en werkt slijmoplossend \u2014 de basis van dennenbalsem."),
"struikhei":("Arbutine","fenolglycosiden","Wordt in de blaas omgezet in een licht ontsmettende stof; dezelfde weg als bij beredruif."),
"dophei":("Arbutine","fenolglycosiden","Als struikhei, maar de standplaats is beschermd \u2014 herkennen is hier het gebruik."),
"ijzerhard":("Verbenaline","irido\u00efden","Bitter en licht samentrekkend op de baarmoeder \u2014 vandaar het verbod tijdens zwangerschap."),
"longkruid":("Slijmstoffen en allanto\u00efne","polysachariden","Verzachtend bij droge hoest; de witte vlekken op het blad hadden er niets mee te maken."),
"muizenoor":("Umbelliferon","cumarinen","Licht antibacterieel; een van de weinige planten waarin deze stof in bruikbare hoeveelheid zit."),
"tandzaad":("Looistoffen en polyacetylenen","tannines","Samentrekkend bij lichte diarree en verzachtend op de huid in een badkruid."),
"moerasandoorn":("Betaine en looistoffen","tannines","Wondhelend; de oude naam wondkruid slaat op precies dit gebruik."),
"bosandoorn":("Looistoffen en stachydrine","tannines","Sterk samentrekkend, maar de doordringende stank maakt inwendig gebruik onaantrekkelijk."),
"blauwglidkruid":("Baicaline en scutellarine","flavono\u00efden","Kalmerend op het zenuwstelsel; de Amerikaanse verwant is in de kruidenhandel bekender."),
"stinkendeballote":("Marrubiine-achtige diterpenen","bitterstoffen","Kalmerend en misselijkheidremmend; drogen haalt de stank eruit zonder de werking weg te nemen."),
"borstelkrans":("Carvacrol en thymol","fenolen","Dezelfde stoffen als in marjolein en tijm, in lagere concentratie."),
"gamander":("Teucriine","diterpenen","Bitter, maar sommige gamandersoorten belasten bij langdurig gebruik de lever \u2014 vandaar de terughoudendheid."),
"grotepimpernel":("Sanguisorbine en looistoffen","tannines","Zeer looistofrijk; <i>Sanguisorba</i> betekent bloedopslurpend, naar het stelpen van bloedingen."),
"ossentong":("Pyrrolizidine-alkalo\u00efden en allanto\u00efne","alkalo\u00efden","Allanto\u00efne heelt de huid, de alkalo\u00efden belasten de lever \u2014 samen de reden voor uitsluitend uitwendig gebruik."),
"penningkruid":("Looistoffen en saponinen","tannines","Samentrekkend en licht wondhelend; het gebruik ligt vooral op de huid."),
"canadeseguldenroede":("Rutine en saponinen","flavono\u00efden","Waterafdrijvend zonder kalium te verliezen \u2014 daarom een klassiek nierkruid."),
"witteabeel":("Salicine en populine","fenolglycosiden","Als bij de andere populieren; de knoppen bevatten daarnaast de balsemharsen voor zalf."),
"grauwewilg":("Salicine","fenolglycosiden","Dezelfde stof als bij de andere wilgen, met dezelfde bezwaren bij aspirineovergevoeligheid."),
"heelblaadjes":("Looistoffen en inuline","tannines","Samentrekkend bij darmklachten; de soortnaam <i>dysenterica</i> verwijst naar dat gebruik."),
"kruisbladwalstro":("Asperulosiden","irido\u00efden","Als bij kleefkruid: breken bij verhitting af, dus zacht behandelen."),
"canadapopulier":("Salicine en balsemharsen","fenolglycosiden","Minder geurig dan de zwarte populier maar met dezelfde stoffen in de knop."),
"huislook":("Slijmstoffen en looistoffen","polysachariden","Het bladsap verzacht en trekt tegelijk samen \u2014 vandaar het gebruik als alo\u00eb-vervanger."),
"bergsteentijm":("Pulegon en menthon","terpenen","Verklaart de sterke munt-tijmgeur; pulegon is de reden om spaarzaam te doseren."),
"geelwalstro":("Cumarine en asperulosiden","cumarinen","Cumarine geeft de hooigeur en werkt als stremsel bij het kaasmaken."),
"veenmos":("Sphagnol en fenolzuren","fenolzuren","Het mos is zuur en zuigt sterk; samen remt dat bacteriegroei \u2014 de reden voor het gebruik als wondverband."),
"lateguldenroede":("Rutine en saponinen","flavono\u00efden","Als de Canadese guldenroede; de stengel is kaal in plaats van behaard, de werking dezelfde."),
"grauweabeel":("Salicine en populine","fenolglycosiden","Kruising van witte abeel en ratelpopulier, met de stoffen van allebei."),
}
regels = "\n".join(' %-24s {stof:%s, grp:%s, uitleg:%s},' % (
    k+':', '"'+a.replace('"','\\"')+'"', '"'+b.replace('"','\\"')+'"', '"'+c.replace('"','\\"')+'"')
    for k,(a,b,c) in sorted(N.items()))
s = rep(s, ' brandnetel:      {stof:"Histamine en mierenzuur"',
        regels + '\n brandnetel:      {stof:"Histamine en mierenzuur"')
open(src, "w", encoding="utf-8").write(s)
print("stoffen toegevoegd:", len(N))
